### ISSUE TITLE
node启动服务出错

### ISSUE THREAD

**Issue by LouisaNikita** [yjj5855/node-vue-server-webpack#3]
node启动服务出错，具体如下，不应该是代码问题，我按照步骤弄得，是不是缺少了什么？
错误信息如下：

/projects/routertest/node-vue-server-webpack/server/routes/cookbook.js:11
        var classes = await, getCookbookClass_1 = ();
                                                    ^

SyntaxError: Expected () to start arrow function, but got ';' instead of '=>'
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/luyi/projects/routertest/node-vue-server-webpack/server.js:9:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by yjj5855** [comment]
服务端js文件是用过ts编译出来的 你这里看到的和我这里的不一样 是不是自己改过了 还是你的ts版本太低？

**Comment by tobeacoder** [comment]
同样启动错误，tsc版本：message TS6029: Version 1.5.3
tsd版本： tsd 0.6.5，是不是这两个版本过低？

**Comment by 12345laohu** [comment]
tsc 错误信息如下：
server/lib/apiService.ts(7,1): error TS1128: Declaration or statement expected.
server/lib/apiService.ts(7,14): error TS1005: ';' expected.
server/lib/apiService.ts(24,1): error TS1128: Declaration or statement expected.
server/lib/apiService.ts(24,14): error TS1005: ';' expected.
server/routes/cookbook.ts(9,1): error TS1128: Declaration or statement expected.
server/routes/cookbook.ts(9,14): error TS1005: ';' expected.
server/routes/cookbook.ts(17,29): error TS1005: ',' expected.
server/routes/cookbook.ts(17,45): error TS1005: '=' expected.
server/routes/cookbook.ts(17,46): error TS1109: Expression expected.
server/routes/cookbook.ts(18,26): error TS1005: ',' expected.
server/routes/cookbook.ts(18,41): error TS1005: '=' expected.
server/typings/request/request.d.ts(23,31): error TS1005: '=' expected.
server/typings/request/request.d.ts(27,33): error TS1005: '=' expected.
server/typings/request/request.d.ts(31,34): error TS1005: '=' expected.
server/typings/request/request.d.ts(35,33): error TS1005: '=' expected.
server/typings/request/request.d.ts(39,34): error TS1005: '=' expected.
server/typings/request/request.d.ts(43,35): error TS1005: '=' expected.
server/typings/request/request.d.ts(47,33): error TS1005: '=' expected.
server/typings/request/request.d.ts(104,41): error TS1005: ';' expected.

**Comment by 12345laohu** [comment]
同样启动错误，tsc版本：message TS6029: Version 1.5.3
tsd版本： tsd 0.6.5，是不是这两个版本过低？

**Comment by yjj5855** [comment]
我的ts版本是1.8.7
tsc版本是1.7.5
tsd版本是0.6.5

**Comment by confidence68** [comment]
我安装也遇到相同的问题！

**Comment by yjj5855** [comment]
@confidence68 Vue2.0 原生支持服务端渲染了 去看2.0的文档吧 这个项目不维护了。。。
